# see https://edu.chainguard.dev/chainguard/migration/migrating-php/

services:
  app:
    container_name: laranab-app
    image: cgr.dev/chainguard/laravel:latest-dev
    restart: unless-stopped
    volumes:
      - ./app:/app
    env_file:
      - .env
    networks:
      - wolfi

  nginx:
    container_name: laranab-nginx
    image: cgr.dev/chainguard/nginx
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8080"
    networks:
      - wolfi

  mariadb:
    container_name: laranab-mariadb
    image: cgr.dev/chainguard/mariadb
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - wolfi

  scheduler:
    container_name: laranab-scheduler
    image: cgr.dev/chainguard/laravel:latest-dev
    restart: unless-stopped
    volumes:
      - ./app:/app
    env_file:
      - .env
    entrypoint: ["php", "artisan", "schedule:work"]
    networks:
      - wolfi

networks:
  wolfi:
    driver: bridge